plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'local.ytk.app.ds'
version = '0.2.2'

repositories {
    mavenCentral()
    maven {
        url 'https://jitpack.io'
        content { includeGroup "com.github.SuperYoshi10000" }
    }
    maven {
        url "https://libraries.minecraft.net"
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    
    implementation 'org.apache.commons:commons-lang3:3.18.0'
    implementation 'org.apache.commons:commons-collections4:4.4'
    implementation 'commons-cli:commons-cli:1.11.0'
    
    implementation 'it.unimi.dsi:fastutil:8.5.13'
    implementation 'io.netty:netty-all:4.2.16.Final'
    implementation 'com.mojang:brigadier:1.0.18'
    implementation 'com.mojang:datafixerupper:1.0.21'
    
    // Jackson
    implementation platform('tools.jackson:jackson-bom:3.2.0')
    
    implementation 'tools.jackson.core:jackson-core'
    implementation 'tools.jackson.core:jackson-databind'
//    implementation 'tools.jackson.core:jackson-annotations'
    
    implementation 'tools.jackson.dataformat:jackson-dataformat-yaml'
    implementation 'tools.jackson.dataformat:jackson-dataformat-xml'
    implementation 'tools.jackson.dataformat:jackson-dataformat-cbor'
    implementation 'tools.jackson.dataformat:jackson-dataformat-smile'
    implementation 'tools.jackson.dataformat:jackson-dataformat-properties'
    implementation 'tools.jackson.dataformat:jackson-dataformat-csv'
    implementation 'tools.jackson.dataformat:jackson-dataformat-toml'
    implementation 'tools.jackson.dataformat:jackson-dataformat-avro'
    implementation 'tools.jackson.dataformat:jackson-dataformat-protobuf'
    implementation 'tools.jackson.dataformat:jackson-dataformat-ion'
    
//    implementation 'de.undercouch:bson4jackson:3.2.0'
//    implementation 'com.siemens.ct.exi:exificient-for-json:1.0.1-SNAPSHOT'
//    implementation 'org.msgpack:jackson-dataformat-msgpack:0.9.12'
    
    
    implementation 'com.github.SuperYoshi10000:JavaUtils:0.1.2'
    
    compileOnly 'org.jetbrains:annotations:26.0.2'
    
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}
jar {
    manifest {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        attributes(
                'Main-Class': 'local.ytk.app.ds.Main'
        )
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

publishing {
    publications {
        dataSerializer(MavenPublication) {
            from components.java
        }
    }
    
    repositories {
        maven {
//            name = 'dataSerializer'
            url = layout.buildDirectory.dir("repo")
        }
    }
}